# Generated by Django 4.2.10 on 2024-02-17 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affordability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(blank=True, max_length=45, null=True, verbose_name='شغل')),
            ],
        ),
        migrations.CreateModel(
            name='level_of_life',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neme', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='marital_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='membership_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45, verbose_name='نام')),
                ('last_name', models.CharField(max_length=45, verbose_name='خانوادگی')),
                ('user_name', models.CharField(blank=True, max_length=45, null=True, verbose_name='کد عضویت')),
                ('national_code', models.CharField(blank=True, max_length=45, null=True, verbose_name='کدملی')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='ایا فعاله؟')),
                ('financial_situation', models.IntegerField(blank=True, null=True)),
                ('image', models.CharField(max_length=100)),
                ('representative', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('join_at', models.DateField(auto_now_add=True)),
                ('affordability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CRM.affordability')),
                ('membership_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CRM.membership_type', verbose_name='نوع فعالیت')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('monasebat', models.CharField(blank=True, max_length=45, null=True)),
                ('pointcol', models.CharField(blank=True, max_length=45, null=True)),
                ('users_idusers', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CRM.users')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=45)),
                ('identity', models.CharField(blank=True, max_length=45, null=True)),
                ('pkuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CRM.users')),
            ],
        ),
        migrations.AddField(
            model_name='affordability',
            name='level_of_life',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CRM.level_of_life'),
        ),
        migrations.AddField(
            model_name='affordability',
            name='marital_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CRM.marital_status', verbose_name='وضعیت مالی'),
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('number_of_region', models.IntegerField(blank=True, null=True)),
                ('street', models.CharField(blank=True, max_length=15, null=True)),
                ('detail_adress', models.CharField(blank=True, max_length=45, null=True)),
                ('idusers', models.ForeignKey(db_column='idusers', on_delete=django.db.models.deletion.DO_NOTHING, to='CRM.users')),
            ],
        ),
    ]
